apiVersion: apps/v1
kind: DaemonSet
metadata:
   name: monitoring-daemonset
   labels:
     name: myapp
     type: front-end
spec:
  template:
    metadata:     
       labels:
         app: monitoring-agent
    spec:
      containers:
        - name: monitoring-agent
          image: monitoring-agent     
    selector:
     matchLabels:
        app: monitoring-agent
