apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constaint
spec:
  limits:
   - default:
       cpu: 500m
     defaultRequest:
       cpu: 500m
     max:
       cpu: "1"
     min:
       cpu: 100m
     type: Container
     
#--------------------------------------------------------------------------------

apiVersion: v1
kind: LimitRange
metadata:
  name: memory-resource-constaint
spec:
  limits:
   - default:
       memory: 500m
     defaultRequest:
       memory: 500m
     max:
       memory: "1"
     min:
       memory: 100m
     type: Container
       
