apiVersion: v1
kind: Pod
metadata:
  name: my-secret-app
spec:
  containers:
    - name: my-secret-app
      image: secret-image
      ports:
        containerPort: 8080
      envFrom:
        - secretRef:
              name: my-secret-app
              
    Note: secret ref file is we created to store the secret is secret-data.yaml
