apiVersion: v1
kind: Service
metadata:
    name: resukt-service
    labels:
       name: result-service
       app: demo-voting-app
selector:
     type: NodePort
     ports:
       - port: 80
         targetPort: 80
         nodePort: 30005
     selector:
        name: result-app-pod
        app: demo-voting-app
